# Generated by Django 5.1.15 on 2026-09-02 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('post', models.CharField(choices=[('SENATEUR', 'Sénateur (Département du Nord-Ouest)'), ('DEPUTE', 'Député (Circonscription)'), ('MAIRE', 'Maire (Commune)'), ('CASEC', 'CASEC (Section Communale)'), ('ASEC', 'ASEC (Section Communale)'), ('DELEGUE_VILLE', 'Délégué de Ville (Ville / Quartier)')], max_length=30, verbose_name='Poste électif')),
                ('commune', models.CharField(choices=[('PORT_DE_PAIX', 'Port-de-Paix'), ('SAINT_LOUIS_DU_NORD', 'Saint-Louis-du-Nord'), ('JEAN_RABEL', 'Jean-Rabel'), ('MOLE_SAINT_NICOLAS', 'Môle-Saint-Nicolas'), ('BOMBARDOPOLIS', 'Bombardopolis'), ('BAIE_DE_HENNE', 'Baie-de-Henne'), ('BASSIN_BLEU', 'Bassin-Bleu'), ('ANSE_A_FOLEUR', 'Anse-à-Foleur'), ('CHANSOLME', 'Chansolme'), ('LA_TORTUE', 'La Tortue')], max_length=50, verbose_name='Commune de rattachement')),
                ('section_or_city', models.CharField(blank=True, default='', help_text='Obligatoire pour les postes de CASEC, ASEC ou Délégué de Ville', max_length=150, verbose_name='Section communale ou Ville / Quartier')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/', verbose_name='Photo officielle')),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan de campagne')),
                ('biography', models.TextField(verbose_name='Biographie & Parcours')),
                ('platform_priorities', models.TextField(help_text='Les 3 à 4 axes majeurs de votre programme', verbose_name='Priorités / Programme')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('DISABLED', 'Désactivé')], default='PENDING', max_length=20, verbose_name='Statut de la candidature')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Motif de rejet ou observation')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Candidat',
                'verbose_name_plural': 'Profils Candidats',
                'ordering': ['-created_at'],
            },
        ),
    ]
