# Generated by Django 5.1.15 on 2026-09-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_open', models.BooleanField(default=True, verbose_name='Enskripsyon kandida yo louvri ?')),
                ('registration_deadline', models.DateTimeField(verbose_name='Dat & Lè limit enskripsyon kandida yo')),
                ('is_voting_open', models.BooleanField(default=False, verbose_name='Faz vòt la louvri ?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigirasyon Sondaj la',
                'verbose_name_plural': 'Konfigirasyon Sondaj la',
            },
        ),
    ]
