# Generated by Django 5.1.15 on 2026-09-02 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_surveyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commune', models.CharField(choices=[('PORT_DE_PAIX', 'Port-de-Paix'), ('SAINT_LOUIS_DU_NORD', 'Saint-Louis-du-Nord'), ('JEAN_RABEL', 'Jean-Rabel'), ('MOLE_SAINT_NICOLAS', 'Môle-Saint-Nicolas'), ('BOMBARDOPOLIS', 'Bombardopolis'), ('BAIE_DE_HENNE', 'Baie-de-Henne'), ('BASSIN_BLEU', 'Bassin-Bleu'), ('ANSE_A_FOLEUR', 'Anse-à-Foleur'), ('CHANSOLME', 'Chansolme'), ('LA_TORTUE', 'La Tortue')], max_length=50, verbose_name='Komin de rezidans (Verouye)')),
                ('commune_locked', models.BooleanField(default=True, help_text='Yon fwa enskri, patisipan an pa ka chanje komin li ankò', verbose_name='Komin verouye definitivman')),
                ('has_voted_senateur', models.BooleanField(default=False, verbose_name='Vote pou Sénateur')),
                ('has_voted_depute', models.BooleanField(default=False, verbose_name='Vote pou Député')),
                ('has_voted_maire', models.BooleanField(default=False, verbose_name='Vote pou Maire')),
                ('has_voted_casec', models.BooleanField(default=False, verbose_name='Vote pou CASEC')),
                ('has_voted_delegue', models.BooleanField(default=False, verbose_name='Vote pou Délégué de Ville')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL, verbose_name='Koneksyon itilizatè')),
            ],
            options={
                'verbose_name': 'Profil Patisipan / Elektè',
                'verbose_name_plural': 'Profils Patisipan yo',
                'ordering': ['-created_at'],
            },
        ),
    ]
