# Generated by Django 5.1.15 on 2026-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_voterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='commune',
            field=models.CharField(max_length=100, verbose_name='Commune de rattachement'),
        ),
    ]
