# Generated by Django 4.2.7 on 2026-09-05 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_candidateprofile_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Anpwent inik aparèy la (Device Fingerprint)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adrès IP aparèy la')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent aparèy la')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CANDIDATE', 'Candidat'), ('VOTER', 'Participant / Électeur')], max_length=20, verbose_name='Ròl nan enskripsyon an')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dat enskripsyon aparèy la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Kont itilizatè anrejistre')),
            ],
            options={
                'verbose_name': 'Enskripsyon Aparèy',
                'verbose_name_plural': 'Enskripsyon Aparèy yo',
                'ordering': ['-created_at'],
            },
        ),
    ]
