# Generated by Django 4.2.7 on 2026-09-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deviceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Adrès Imèl Ofisyèl Kandida a'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Chak kont dwe gen yon adrès imèl inik', max_length=254, null=True, unique=True, verbose_name='Adrès Imèl Inik'),
        ),
    ]
