# Generated by Django 5.1.15 on 2026-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidateprofile_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregistration',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Sipè Administratè'), ('MODERATOR', 'Moderatè / Analis Dosye'), ('OPERATOR', 'Operatè Saisie'), ('COMMUNICATOR', 'Ofisye Kominikasyon'), ('CANDIDATE', 'Kandida'), ('VOTER', 'Patisipan / Électeur')], max_length=20, verbose_name='Ròl nan enskripsyon an'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Sipè Administratè'), ('MODERATOR', 'Moderatè / Analis Dosye'), ('OPERATOR', 'Operatè Saisie'), ('COMMUNICATOR', 'Ofisye Kominikasyon'), ('CANDIDATE', 'Kandida'), ('VOTER', 'Patisipan / Électeur')], default='VOTER', max_length=20, verbose_name='Rôle'),
        ),
    ]
