# Generated by Django 4.2.7 on 2026-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_deviceregistration_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_bank_info',
            field=models.TextField(blank=True, default='Unibank HTG: 123-4567-890123 | Sogebank USD: 987-6543-210987', verbose_name='Enfòmasyon Kont Labank'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_bank_name',
            field=models.CharField(blank=True, default='Inisyativ Sitwayen Nòdwès', max_length=150, verbose_name='Non Mèt Kont Labank'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_cashapp_tag',
            field=models.CharField(blank=True, default='$SondageNordOuest', max_length=100, verbose_name='Tag CashApp ($cashtag)'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_moncash_name',
            field=models.CharField(blank=True, default='Kowòdinasyon Sondaj Nòdwès', max_length=150, verbose_name='Non Mèt Kont MonCash'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_moncash_number',
            field=models.CharField(blank=True, default='+509 37 00 0000', max_length=50, verbose_name='Nimewo MonCash'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_natcash_name',
            field=models.CharField(blank=True, default='Kowòdinasyon Sondaj Nòdwès', max_length=150, verbose_name='Non Mèt Kont Natcash'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_natcash_number',
            field=models.CharField(blank=True, default='+509 40 00 0000', max_length=50, verbose_name='Nimewo Natcash'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_zelle_info',
            field=models.CharField(blank=True, default='sondagenordouest@gmail.com', max_length=150, verbose_name='Imèl / Nimewo Zelle'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='donation_zelle_name',
            field=models.CharField(blank=True, default='Nord-Ouest Citizen Civic Initiative', max_length=150, verbose_name='Non Mèt Kont Zelle'),
        ),
    ]
