# Generated by Django 4.2.7 on 2026-09-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_surveyconfig_donation_bank_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='withdrawal_reason',
            field=models.TextField(blank=True, default='', verbose_name='Rezon retrè kandidati a'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='withdrawal_requested',
            field=models.BooleanField(default=False, verbose_name='Demann retrè soumèt'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='withdrawal_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dat demand retrè a'),
        ),
    ]
