# Generated by Django 4.2.7 on 2026-09-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_candidateprofile_withdrawal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyconfig',
            name='show_official_publications',
            field=models.BooleanField(default=True, verbose_name='Afiche Seksyon Kominike ak Piblikasyon yo sou Paj Akèy ?'),
        ),
    ]
