# Generated by Django 4.2.7 on 2026-09-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_surveyconfig_show_official_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cartel_member2_name',
            field=models.CharField(blank=True, default='', help_text='Non ak Prenon dezyèm manm kartèl la', max_length=150, verbose_name='1e Majistra Adjwen (1er Adjoint)'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cartel_member3_name',
            field=models.CharField(blank=True, default='', help_text='Non ak Prenon twazyèm manm kartèl la', max_length=150, verbose_name='2e Majistra Adjwen (2ème Adjoint)'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cartel_name',
            field=models.CharField(blank=True, default='', help_text='Egzanp : Kartèl Tèt Ansanm pou Pòdepè', max_length=150, verbose_name='Non Kartèl la / Bannè Politik'),
        ),
    ]
