# Generated by Django 4.2.7 on 2026-09-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_candidateprofile_cartel_member2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyconfig',
            name='support_email',
            field=models.EmailField(blank=True, default='sondagenordouest@gmail.com', max_length=254, verbose_name='Imèl Sipò Ofisyèl'),
        ),
        migrations.AddField(
            model_name='surveyconfig',
            name='support_whatsapp',
            field=models.CharField(blank=True, default='+50937000000', max_length=30, verbose_name='Nimewo WhatsApp Sipò (fòma entènasyonal, ex: +50937000000)'),
        ),
    ]
