# Generated by Django 5.1.15 on 2026-09-02 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_voterprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.CharField(choices=[('SENATEUR', 'Sénateur (Département du Nord-Ouest)'), ('DEPUTE', 'Député (Circonscription)'), ('MAIRE', 'Maire (Commune)'), ('CASEC', 'CASEC (Section Communale)'), ('ASEC', 'ASEC (Section Communale)'), ('DELEGUE_VILLE', 'Délégué de Ville (Ville / Quartier)')], max_length=30, verbose_name='Pòs Elektif')),
                ('commune', models.CharField(choices=[('PORT_DE_PAIX', 'Port-de-Paix'), ('SAINT_LOUIS_DU_NORD', 'Saint-Louis-du-Nord'), ('JEAN_RABEL', 'Jean-Rabel'), ('MOLE_SAINT_NICOLAS', 'Môle-Saint-Nicolas'), ('BOMBARDOPOLIS', 'Bombardopolis'), ('BAIE_DE_HENNE', 'Baie-de-Henne'), ('BASSIN_BLEU', 'Bassin-Bleu'), ('ANSE_A_FOLEUR', 'Anse-à-Foleur'), ('CHANSOLME', 'Chansolme'), ('LA_TORTUE', 'La Tortue')], max_length=50, verbose_name='Komin kote vòt la anrejistre')),
                ('receipt_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Kòd Resi Vòt (UUID)')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hachaj IP anonimize')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dat & Lè Vòt la')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='accounts.candidateprofile', verbose_name='Kandida chwazi')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Patisipan / Elektè')),
            ],
            options={
                'verbose_name': 'Vòt Preliminè',
                'verbose_name_plural': 'Vòt Preliminè yo',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('voter', 'post'), name='unique_vote_per_voter_per_post')],
            },
        ),
    ]
