# Generated by Django 4.2.7 on 2026-09-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Anpwent inik aparèy vòt la'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('device_fingerprint__gt', '')), fields=('device_fingerprint', 'post'), name='unique_vote_per_device_per_post'),
        ),
    ]
