# Generated by Django 5.1.15 on 2026-09-11 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_vote_device_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tit Pòs la')),
                ('content', models.TextField(verbose_name='Kontni / Tèks Kominike a')),
                ('category', models.CharField(choices=[('COMMUNIQUE', 'Kominike Ofisyèl'), ('ALERT', 'Alèt Enpòtan'), ('UPDATE', 'Mizajou Kalandriye'), ('GENERAL', 'Enfòmasyon Jeneral')], default='COMMUNIQUE', max_length=30, verbose_name='Kategori')),
                ('author_name', models.CharField(blank=True, default='Komisyon Elektoral Nòdwès', max_length=150, verbose_name='Non Otè a')),
                ('is_published', models.BooleanField(default=True, verbose_name='Pibliye')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dat kreyasyon')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dènye modifikasyon')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Otè')),
            ],
            options={
                'verbose_name': 'Kominike & Piblikasyon',
                'verbose_name_plural': 'Kominike & Piblikasyon yo',
                'ordering': ['-created_at'],
            },
        ),
    ]
