# Generated by Django 4.2.7 on 2026-09-12 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_publicannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=150, verbose_name='Non Donatè')),
                ('donor_contact', models.CharField(max_length=100, verbose_name='Telefòn oswa Imèl')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montan Don')),
                ('currency', models.CharField(default='HTG', max_length=10, verbose_name='Deviz (HTG/USD)')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Metòd Peman')),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=120, verbose_name='Kòd Referans / Tranzaksyon')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mesaj Ankourajman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dat Kreyasyon')),
            ],
            options={
                'verbose_name': 'Donasyon Sitwayen',
                'verbose_name_plural': 'Donasyon Sitwayen yo',
                'ordering': ['-created_at'],
            },
        ),
    ]
