# Generated by Django 5.1.15 on 2026-09-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Kle Tradiksyon (Key)')),
                ('category', models.CharField(blank=True, db_index=True, default='GENERAL', max_length=80, verbose_name='Kategori / Seksyon')),
                ('text_ht', models.TextField(verbose_name='Tèks Kreyòl (HT)')),
                ('text_fr', models.TextField(blank=True, default='', verbose_name='Tèks Français (FR)')),
                ('text_en', models.TextField(blank=True, default='', verbose_name='Tèks English (EN)')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Deskripsyon kote li itilize')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dènye modifikasyon')),
            ],
            options={
                'verbose_name': 'Tradiksyon Platfòm nan',
                'verbose_name_plural': 'Tradiksyon Platfòm nan yo',
                'ordering': ['category', 'key'],
            },
        ),
    ]
